export const AUTHOR: any = {
  1: {
    fullName: "Mahyar goudarzi",
    books: [
      {
        title: "Typescript book",
        description: "Learn in depth the Typescript language, build practical real-world projects",
        imageUrl: "https://url.com/",
        category: "PROGRAMMING",
        url: "typescript-definitive",
        price: 50,
      },
      {
        title: "JavaScript book",
        description: "Master JavaScript and become proficient in front-end and back-end development",
        imageUrl: "https://url.com/",
        category: "PROGRAMMING",
        url: "javascript-master",
        price: 45,
      },
      {
        title: "Python book",
        description: "Dive into Python programming and explore its extensive libraries and frameworks",
        imageUrl: "https://url.com/",
        category: "PROGRAMMING",
        url: "python-essentials",
        price: 55,
      },
      {
        title: "Java book",
        description: "Become proficient in Java programming language and its ecosystem",
        imageUrl: "https://url.com/",
        category: "PROGRAMMING",
        url: "java-mastery",
        price: 60,
      },
      {
        title: "C# book",
        description: "Learn C# language and build robust applications on the .NET platform",
        imageUrl: "https://url.com/",
        category: "PROGRAMMING",
        url: "csharp-in-depth",
        price: 55,
      },
      {
        title: "HTML & CSS book",
        description: "Master HTML and CSS to create stunning and responsive web pages",
        imageUrl: "https://url.com/",
        category: "WEB DEVELOPMENT",
        url: "html-css-pro",
        price: 40,
      },
      {
        title: "React.js book",
        description: "Build dynamic and interactive user interfaces with React.js library",
        imageUrl: "https://url.com/",
        category: "WEB DEVELOPMENT",
        url: "react-essentials",
        price: 50,
      },
      {
        title: "Angular book",
        description: "Master Angular framework to create modern and scalable web applications",
        imageUrl: "https://url.com/",
        category: "WEB DEVELOPMENT",
        url: "angular-mastery",
        price: 60,
      },
      {
        title: "Vue.js book",
        description: "Learn Vue.js and build reactive web applications with ease",
        imageUrl: "https://url.com/",
        category: "WEB DEVELOPMENT",
        url: "vue-quickstart",
        price: 45,
      },
      {
        title: "Node.js book",
        description: "Master Node.js and build scalable server-side applications",
        imageUrl: "https://url.com/",
        category: "WEB DEVELOPMENT",
        url: "nodejs-in-action",
        price: 55,
      },
      {
        title: "Docker book",
        description: "Learn Docker and containerize your applications for easier deployment",
        imageUrl: "https://url.com/",
        category: "DEVOPS",
        url: "docker-essentials",
        price: 40,
      },
      {
        title: "Linux book",
        description: "Dive into Linux operating system and become proficient in system administration",
        imageUrl: "https://url.com/",
        category: "OPERATING SYSTEMS",
        url: "linux-essentials",
        price: 40,
      },
      {
        title: "Windows book",
        description: "Master Windows operating system and manage enterprise environments effectively",
        imageUrl: "https://url.com/",
        category: "OPERATING SYSTEMS",
        url: "windows-mastery",
        price: 45,
      },
      {
        title: "MacOS book",
        description: "Explore MacOS operating system and its features for productivity and creativity",
        imageUrl: "https://url.com/",
        category: "OPERATING SYSTEMS",
        url: "macos-essentials",
        price: 50,
      },
      {
        title: "Networking book",
        description: "Master networking fundamentals and design robust and secure networks",
        imageUrl: "https://url.com/",
        category: "NETWORKING",
        url: "networking-basics",
        price: 55,
      },
      {
        title: "Cybersecurity book",
        description: "Dive into cybersecurity and protect your systems from cyber threats",
        imageUrl: "https://url.com/",
        category: "NETWORKING",
        url: "cybersecurity-guide",
        price: 60,
      },
      {
        title: "Cloud Security book",
        description: "Explore cloud security principles and best practices for securing cloud environments",
        imageUrl: "https://url.com/",
        category: "NETWORKING",
        url: "cloud-security-essentials",
        price: 55,
      },
      {
        title: "Wireless Networking book",
        description: "Learn wireless networking concepts and design reliable wireless networks",
        imageUrl: "https://url.com/",
        category: "NETWORKING",
        url: "wireless-networking-basics",
        price: 50,
      },
      {
        title: "Digital Marketing book",
        description: "Explore digital marketing strategies and reach your target audience effectively",
        imageUrl: "https://url.com/",
        category: "MARKETING",
        url: "digital-marketing-guide",
        price: 45,
      },
    ],
  },
  2: {
    fullName: "Abolfazl mikaniki",
    books: [
      {
        title: "Kubernetes book",
        description: "Master Kubernetes and orchestrate containerized applications at scale",
        imageUrl: "https://url.com/",
        category: "DEVOPS",
        uniqueSlug: "kubernetes-in-depth",
        price: 60,
      },
      {
        title: "Git book",
        description: "Learn Git version control system and collaborate effectively on projects",
        imageUrl: "https://url.com/",
        category: "DEVOPS",
        uniqueSlug: "git-mastery",
        price: 35,
      },
      {
        title: "AWS book",
        description: "Explore Amazon Web Services and leverage its cloud computing services",
        imageUrl: "https://url.com/",
        category: "CLOUD COMPUTING",
        uniqueSlug: "aws-essentials",
        price: 55,
      },
      {
        title: "Azure book",
        description: "Master Microsoft Azure cloud platform and build scalable solutions",
        imageUrl: "https://url.com/",
        category: "CLOUD COMPUTING",
        uniqueSlug: "azure-in-action",
        price: 60,
      },
      {
        title: "Google Cloud book",
        description: "Explore Google Cloud Platform and its suite of cloud computing services",
        imageUrl: "https://url.com/",
        category: "CLOUD COMPUTING",
        uniqueSlug: "google-cloud-guide",
        price: 55,
      },
      {
        title: "Machine Learning book",
        description: "Dive into machine learning algorithms and build intelligent applications",
        imageUrl: "https://url.com/",
        category: "DATA SCIENCE",
        uniqueSlug: "ml-essentials",
        price: 65,
      },
      {
        title: "Deep Learning book",
        description: "Explore deep learning techniques and build advanced neural networks",
        imageUrl: "https://url.com/",
        category: "DATA SCIENCE",
        uniqueSlug: "deep-learning-master",
        price: 70,
      },
      {
        title: "Data Visualization book",
        description: "Learn data visualization techniques and communicate insights effectively",
        imageUrl: "https://url.com/",
        category: "DATA SCIENCE",
        uniqueSlug: "data-viz-guide",
        price: 50,
      },
      {
        title: "SQL book",
        description: "Master SQL language and manage relational databases effectively",
        imageUrl: "https://url.com/",
        category: "DATABASES",
        uniqueSlug: "sql-essentials",
        price: 40,
      },
      {
        title: "NoSQL book",
        description: "Explore NoSQL databases and choose the right one for your applications",
        imageUrl: "https://url.com/",
        category: "DATABASES",
        uniqueSlug: "nosql-guide",
        price: 45,
      },
      {
        title: "MongoDB book",
        description: "Learn MongoDB and build scalable and flexible document-based databases",
        imageUrl: "https://url.com/",
        category: "DATABASES",
        uniqueSlug: "mongodb-essentials",
        price: 50,
      },
      {
        title: "SEO book",
        description: "Master search engine optimization techniques and improve your website's visibility",
        imageUrl: "https://url.com/",
        category: "MARKETING",
        uniqueSlug: "seo-essentials",
        price: 40,
      },
      {
        title: "Content Marketing book",
        description: "Learn content marketing strategies and create valuable content for your audience",
        imageUrl: "https://url.com/",
        category: "MARKETING",
        uniqueSlug: "content-marketing-mastery",
        price: 50,
      },
      {
        title: "Social Media Marketing book",
        description: "Explore social media marketing tactics and engage with your audience on social platforms",
        imageUrl: "https://url.com/",
        category: "MARKETING",
        uniqueSlug: "social-media-marketing-guide",
        price: 45,
      },
      {
        title: "Email Marketing book",
        description: "Master email marketing strategies and nurture leads effectively through email campaigns",
        imageUrl: "https://url.com/",
        category: "MARKETING",
        uniqueSlug: "email-marketing-essentials",
        price: 40,
      },
      {
        title: "Financial Planning book",
        description: "Learn financial planning principles and manage your finances effectively",
        imageUrl: "https://url.com/",
        category: "FINANCE",
        uniqueSlug: "financial-planning-basics",
        price: 55,
      },
      {
        title: "Investing book",
        description: "Dive into investing strategies and build wealth through smart investment decisions",
        imageUrl: "https://url.com/",
        category: "FINANCE",
        uniqueSlug: "investing-essentials",
        price: 60,
      },
      {
        title: "Retirement Planning book",
        description: "Plan for retirement effectively and secure your financial future",
        imageUrl: "https://url.com/",
        category: "FINANCE",
        uniqueSlug: "retirement-planning-guide",
        price: 50,
      },
      {
        title: "Personal Finance book",
        description: "Learn personal finance principles and achieve financial independence",
        imageUrl: "https://url.com/",
        category: "FINANCE",
        uniqueSlug: "personal-finance-master",
        price: 45,
      },
      {
        title: "Budgeting book",
        description: "Master budgeting techniques and manage your finances effectively",
        imageUrl: "https://url.com/",
        category: "FINANCE",
        uniqueSlug: "budgeting-essentials",
        price: 40,
      },
    ],
  },
  3: {
    fullName: "Ali nemati",
    books: [
      {
        title: "PostgreSQL book",
        description: "Master PostgreSQL and manage advanced relational databases",
        imageUrl: "https://url.com/",
        category: "DATABASES",
        uniqueSlug: "postgresql-in-depth",
        price: 55,
      },
      {
        title: "Blockchain book",
        description: "Explore blockchain technology and build decentralized applications",
        imageUrl: "https://url.com/",
        category: "CRYPTOCURRENCY",
        uniqueSlug: "blockchain-fundamentals",
        price: 60,
      },
      {
        title: "Bitcoin book",
        description: "Dive into Bitcoin and understand its underlying technology and economics",
        imageUrl: "https://url.com/",
        category: "CRYPTOCURRENCY",
        uniqueSlug: "bitcoin-basics",
        price: 50,
      },
      {
        title: "Ethereum book",
        description: "Learn Ethereum blockchain platform and build decentralized applications",
        imageUrl: "https://url.com/",
        category: "CRYPTOCURRENCY",
        uniqueSlug: "ethereum-essentials",
        price: 55,
      },
      {
        title: "Rust book",
        description: "Learn Rust programming language and build fast and secure systems",
        imageUrl: "https://url.com/",
        category: "PROGRAMMING",
        uniqueSlug: "rust-in-action",
        price: 50,
      },
      {
        title: "Go book",
        description: "Master Go programming language and build scalable and concurrent systems",
        imageUrl: "https://url.com/",
        category: "PROGRAMMING",
        uniqueSlug: "go-essentials",
        price: 55,
      },
      {
        title: "Swift book",
        description: "Dive into Swift programming language and build iOS and macOS applications",
        imageUrl: "https://url.com/",
        category: "PROGRAMMING",
        uniqueSlug: "swift-mastery",
        price: 60,
      },
      {
        title: "Kotlin book",
        description: "Learn Kotlin programming language and build modern Android applications",
        imageUrl: "https://url.com/",
        category: "PROGRAMMING",
        uniqueSlug: "kotlin-essentials",
        price: 45,
      },
      {
        title: "PHP book",
        description: "Master PHP programming language and build dynamic web applications",
        imageUrl: "https://url.com/",
        category: "PROGRAMMING",
        uniqueSlug: "php-in-action",
        price: 40,
      },
      {
        title: "Ruby book",
        description: "Learn Ruby programming language and build elegant and expressive applications",
        imageUrl: "https://url.com/",
        category: "PROGRAMMING",
        uniqueSlug: "ruby-essentials",
        price: 45,
      },
      {
        title: "Shell scripting book",
        description: "Master shell scripting and automate system administration tasks",
        imageUrl: "https://url.com/",
        category: "OPERATING SYSTEMS",
        url: "shell-scripting-guide",
        price: 35,
      },
    ],
  },
};

export const USERS = {
  1: {
    email: "test@angular-university.io",
    plainTextPassword: "test",
    passwordSalt: "o61TA7yaJIsa",
    pictureUrl: "https://angular-academy.s3.amazonaws.com/main-logo/main-page-logo-small-hat.png",
    isAdmin: false,
  },
  2: {
    email: "admin@angular-university.io",
    plainTextPassword: "admin",
    passwordSalt: "NydKRjIh4T4X",
    pictureUrl: "https://angular-academy.s3.amazonaws.com/main-logo/main-page-logo-small-hat.png",
    isAdmin: true,
  },
};
